language: go
go:
  - 1.6.1
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/Masterminds/glide
before_script:
  - glide install
script:
  - ./test-with-coverage.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
